### ISSUE TITLE
Recipe Conflict: 2x2 storage drawer / Chest to Storage Crate Upgrade

### ISSUE THREAD

**Issue by ftog-thorgal** [ftog-thorgal/Avant#1]
There is a recipe conflict between:

- Storage Drawers: Drawers 2x2 (#7260/2)
and
- Actually Additions: Chest To Storage Crate Upgrade (#4176)

Screenshot: http://i.imgur.com/LNbu1KU.png

**Comment by glitchn11** [comment]
Hi Thor.  Here is the codt to put into RecipeTweaks.zs:

// # ACTUALLY ADDITIONS #
recipes.remove(<actuallyadditions:itemChestToCrateUpgrade>);
recipes.addShaped(<actuallyadditions:itemChestToCrateUpgrade>, [[<ironchest:BlockIronChest>, <ore:plankWood>, <ironchest:BlockIronChest>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ironchest:BlockIronChest>, <ore:plankWood>, <ironchest:BlockIronChest>]]);
recipes.remove(<actuallyadditions:blockGiantChest>);
recipes.addShaped(<actuallyadditions:blockGiantChest>, [[<ironchest:BlockIronChest>, <ore:plankWood>, <ironchest:BlockIronChest>], [<ore:plankWood>, <actuallyadditions:blockMisc:4>, <ore:plankWood>], [<ironchest:BlockIronChest>, <ore:plankWood>, <ironchest:BlockIronChest>]]);

**Comment by ftog-thorgal** [comment]
https://github.com/ftog-thorgal/Avant/commit/55b54dd7347d87e1ad01ccd020cfc25314086331
