### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by omnidivus** [ftog-thorgal/Avant#10]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 3/30/16 10:20 AM
Description: Tesselating block in world

java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:145)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.build(TRSRBakedModel.java:162)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:63)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:136)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:95)
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175022_a(ElecBlockRendererDispatcher.java:80)
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175018_a(ElecBlockRendererDispatcher.java:43)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
	at gcewing.sg.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:145)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.build(TRSRBakedModel.java:162)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:63)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:136)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:95)
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175022_a(ElecBlockRendererDispatcher.java:80)

-- Block being tesselated --
Details:
	Block type: ID #1498 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.block.BlockToolTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-110,63,313), Chunk: (at 2,3,9 in -7,19; contains blocks -112,0,304 to -97,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175018_a(ElecBlockRendererDispatcher.java:43)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
	at gcewing.sg.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['omnidivus'/20169889, l='MpServer', x=-4.82, y=63.00, z=366.83]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 8.00,64.00,8.00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8908734 game time, 5287348 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 51 total; [EntityZombie['Zombie'/22653147, l='MpServer', x=-34.06, y=44.00, z=407.63], EntityZombie['Zombie'/22653146, l='MpServer', x=-36.50, y=13.00, z=414.50], EntityBat['Bat'/22653149, l='MpServer', x=-39.44, y=43.19, z=423.41], EntityCreeper['Creeper'/22653148, l='MpServer', x=-33.50, y=44.00, z=409.50], EntityPlayerSP['omnidivus'/20169889, l='MpServer', x=-4.82, y=63.00, z=366.83], EntitySkeleton['Skeleton'/22653150, l='MpServer', x=-40.50, y=53.00, z=401.50], EntityCreeper['Creeper'/22650581, l='MpServer', x=-33.50, y=44.00, z=399.50], EntityMegalania['entity.reptilemod.Megalania.name'/22629719, l='MpServer', x=-51.72, y=64.00, z=328.50], EntityCreeper['Creeper'/22650582, l='MpServer', x=-33.50, y=55.00, z=399.50], EntityZombie['Zombie'/22629718, l='MpServer', x=-57.50, y=44.00, z=332.13], EntityCreeper['Creeper'/22629449, l='MpServer', x=-48.50, y=33.00, z=425.50], EntityZombie['Zombie'/22629448, l='MpServer', x=-49.50, y=18.00, z=422.50], EntityBat['Bat'/22648907, l='MpServer', x=-33.25, y=21.10, z=382.75], EntityCreeper['Creeper'/22629451, l='MpServer', x=-63.50, y=41.00, z=312.50], EntitySkeleton['Skeleton'/22648908, l='MpServer', x=-42.50, y=27.00, z=380.50], EntityZombie['Zombie'/22564814, l='MpServer', x=75.50, y=35.00, z=428.50], EntityZombie['Zombie'/22752450, l='MpServer', x=-72.50, y=27.00, z=379.50], EntitySkeleton['Skeleton'/22751812, l='MpServer', x=-69.50, y=41.00, z=327.50], EntityEnderman['Enderman'/22635129, l='MpServer', x=-28.98, y=20.89, z=423.51], EntitySkeleton['Skeleton'/22636792, l='MpServer', x=-40.50, y=53.00, z=367.50], EntityCreeper['Creeper'/22635128, l='MpServer', x=-42.59, y=20.00, z=426.03], EntityBat['Bat'/22635130, l='MpServer', x=-43.50, y=22.71, z=422.46], EntityOtherPlayerMP['Windigo'/196538, l='MpServer', x=56.78, y=68.00, z=-88.50], EntitySpider['Spider'/22635133, l='MpServer', x=-46.50, y=33.00, z=424.50], EntityZombie['Zombie'/22635132, l='MpServer', x=-35.50, y=32.00, z=428.50], EntityZombie['Zombie'/22752894, l='MpServer', x=61.75, y=41.28, z=429.28], EntityZombie['Zombie'/22751869, l='MpServer', x=-3.50, y=30.00, z=420.50], EntitySkeleton['Skeleton'/22635134, l='MpServer', x=-41.50, y=38.00, z=420.50], EntityBat['Bat'/22732541, l='MpServer', x=-58.25, y=21.94, z=414.72], EntityCreeper['Creeper'/22635125, l='MpServer', x=-39.50, y=29.00, z=420.50], EntityBat['Bat'/22733046, l='MpServer', x=-64.63, y=13.34, z=360.19], EntitySkeleton['Skeleton'/22631413, l='MpServer', x=-65.78, y=34.00, z=308.28], EntitySkeleton['Skeleton'/22635127, l='MpServer', x=-33.50, y=30.00, z=420.50], EntityItem['item.item.bone'/22631415, l='MpServer', x=-66.38, y=34.00, z=308.34], EntityCreeper['Creeper'/22635126, l='MpServer', x=-51.09, y=20.00, z=422.31], EntityItem['item.item.bone'/22631414, l='MpServer', x=-67.88, y=33.00, z=306.16], EntityAuraNode['Aura Node'/22653285, l='MpServer', x=43.50, y=73.50, z=440.50], EntityZombie['Zombie'/22554897, l='MpServer', x=-30.47, y=43.00, z=406.94], EntitySkeleton['Skeleton'/22554898, l='MpServer', x=-27.50, y=43.00, z=404.50], EntityBat['Bat'/22671638, l='MpServer', x=-31.10, y=13.02, z=287.41], EntityAuraNode['Aura Node'/22648074, l='MpServer', x=-47.50, y=65.50, z=328.50], EntitySkeleton['Skeleton'/22629645, l='MpServer', x=-62.79, y=23.00, z=368.38], EntityCreeper['Creeper'/22629508, l='MpServer', x=30.50, y=19.00, z=308.50], EntitySkeleton['Skeleton'/22549125, l='MpServer', x=12.50, y=19.00, z=429.50], EntitySpider['Spider'/22493118, l='MpServer', x=56.69, y=26.09, z=327.28], EntityBat['Bat'/22665271, l='MpServer', x=76.72, y=21.38, z=436.56], EntityOtherPlayerMP['gewooneenspeler'/14847270, l='MpServer', x=557.47, y=73.00, z=-386.09], EntityBat['Bat'/22630689, l='MpServer', x=-63.84, y=22.47, z=395.19], EntityCreeper['Creeper'/22630691, l='MpServer', x=-62.50, y=40.00, z=407.50], EntityZombie['Zombie'/22630690, l='MpServer', x=-59.50, y=30.00, z=414.50], EntitySkeleton['Skeleton'/22630692, l='MpServer', x=-48.28, y=38.00, z=414.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1129645088 bytes (1077 MB) / 3398959104 bytes (3241 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1808 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJAAAAAA	Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJAAAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJAAAAAA	OpenComputers|Core{1.6.0.2-beta.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAAAA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJAAAAAA	ActuallyAdditions{1.8.9-r26} [Actually Additions] (ActuallyAdditions-1.8.9-r26.jar) 
	UCHIJAAAAAA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJAAAAAA	ArmorHud{1.0.0} [ArmorHud] (ArmorHud-1.8.9-1.0.0.jar) 
	UCHIJAAAAAA	Aroma1997CoreHelper{1.0.4.1} [Aroma1997Core|Helper] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJAAAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.8.9-1.1.2.0.jar) 
	UCHIJAAAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAAAA	aura{592} [Aura Cascade] (AuraCascade-592.jar) 
	UCHIJAAAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAAAA	Automagy{2.0.1} [Automagy] (Automagy-1.8.9-2.0.1.jar) 
	UCHIJAAAAAA	basemetals{1.7.4} [Base Metals] (BaseMetals-1.7.4.jar) 
	UCHIJAAAAAA	bdlib{1.10.0.31} [BD Lib] (bdlib-1.10.0.31-mc1.8.9.jar) 
	UCHIJAAAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1935-universal.jar) 
	UCHIJAAAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJAAAAAA	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCHIJAAAAAA	JEI{2.28.12.180} [Just Enough Items] (jei_1.8.9-2.28.12.180.jar) 
	UCHIJAAAAAA	BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-20.jar) 
	UCHIJAAAAAA	bookshelfapi{2.3.7} [Bookshelf] (Bookshelf-API-1.8.9-2.3.7.jar) 
	UCHIJAAAAAA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJAAAAAA	Chameleon{1.8.9-1.1.1} [Chameleon] (Chameleon-1.8.9-1.1.1.jar) 
	UCHIJAAAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJAAAAAA	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCHIJAAAAAA	chiselsandbits{8.6} [Chisels & Bits] (chiselsandbits-8.6.jar) 
	UCHIJAAAAAA	ChiselsBytes{0.2} [Chisels & Bytes] (ChiselsBytes-1.8.9-0.2.jar) 
	UCHIJAAAAAA	clayworldgen{v1.0.0} [Clay WorldGen] (ClayWorldGen-1.0.1.jar) 
	UCHIJAAAAAA	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-1.8.8-3.0.2.jar) 
	UCHIJAAAAAA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCHIJAAAAAA	ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
	UCHIJAAAAAA	deepresonance{1.1.4beta22} [DeepResonance] (deepresonance-1.8.9-1.1.4beta22.jar) 
	UCHIJAAAAAA	eirairc{4.9.12} [EiraIRC] (eirairc-mc1.8.9-4.9.12.jar) 
	UCHIJAAAAAA	poweradvantage{1.5.4} [Power Advantage] (PowerAdvantage-1.5.4.jar) 
	UCHIJAAAAAA	electricadvantage{1.1.2} [Electric Advantage] (ElectricAdvantage-1.1.2.jar) 
	UCHIJAAAAAA	enderrift{0.10.0} [Ender-Rift] (EnderRift-0.10.0.jar) 
	UCHIJAAAAAA	enderutilities{0.5.0} [Ender Utilities] (enderutilities-1.8.9-0.5.0.jar) 
	UCHIJAAAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UCHIJAAAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAAAA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJAAAAAA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJAAAAAA	pressure{1.3.0.25} [Pressure Pipes] (pressure-1.3.0.25-mc1.8.9.jar) 
	UCHIJAAAAAA	advgenerators{0.9.19.9} [Advanced Generators] (generators-0.9.19.9-mc1.8.9.jar) 
	UCHIJAAAAAA	gravestone{1.1.3} [Gravestone] (Gravestone Mod 1.1.3.jar) 
	UCHIJAAAAAA	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UCHIJAAAAAA	HydCraft{1.8.9-3.1.65} [Hydraulicraft] (HydCraft-1.8.9-3.1.65-universal.jar) 
	UCHIJAAAAAA	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCHIJAAAAAA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJAAAAAA	ironbackpacks{1.8.9-2.0.5} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.5.jar) 
	UCHIJAAAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAAAA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJAAAAAA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJAAAAAA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCHIJAAAAAA	llor{1.0.7-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.8.9.jar) 
	UCHIJAAAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAAAA	moarcarts{2.0.1-16} [MoarCarts] (moarcarts-1.8.9-2.0.1-16.jar) 
	UCHIJAAAAAA	modtweaker2{1.0.0} [Mod Tweaker 2] (ModTweaker2-1.0.0.jar) 
	UCHIJAAAAAA	numina{0.5.0-001} [Numina] (Numina-0.5.0-001.jar) 
	UCHIJAAAAAA	powersuits{0.11.0-003} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.8.9-0.11.0-003.jar) 
	UCHIJAAAAAA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJAAAAAA	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.8.9.jar) 
	UCHIJAAAAAA	cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurntiureModv3.6.1(1.8.9).jar) 
	UCHIJAAAAAA	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UCHIJAAAAAA	neotech{2.4.4} [NeoTech] (NeoTech-1.8.9-2.4.4.jar) 
	UCHIJAAAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6.jar) 
	UCHIJAAAAAA	notenoughwands{1.3.0} [Not Enough Wands] (notenoughwands-1.8.9-1.3.0.jar) 
	UCHIJAAAAAA	OpenComputers{1.6.0.2-beta.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar) 
	UCHIJAAAAAA	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
	UCHIJAAAAAA	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UCHIJAAAAAA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJAAAAAA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJAAAAAA	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UCHIJAAAAAA	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCHIJAAAAAA	xreliquary{1.3.1.222} [Reliquary] (Reliquary-1.3.1.222.jar) 
	UCHIJAAAAAA	reptilemod{3.1.0} [Reptile Mod] (reptilemod-1.8.9-3.2.1-40.jar) 
	UCHIJAAAAAA	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJAAAAAA	rftools{4.23beta35} [RFTools] (rftools-1.8.9-4.23beta35.jar) 
	UCHIJAAAAAA	rftoolsdim{4.22beta30} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta30.jar) 
	UCHIJAAAAAA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJAAAAAA	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.8.8.jar) 
	UCHIJAAAAAA	routerreborn{1.8.9-3.0.5.14b_universal} [Router Reborn] (RouterReborn-1.8.9-3.0.5.14b_universal.jar) 
	UCHIJAAAAAA	SGCraft{1.11.0} [Greg's SG Craft] (SGCraft-1.11.0-mc1.8.9.jar) 
	UCHIJAAAAAA	steamadvantage{1.5.3} [Steam Advantage] (SteamAdvantage-1.5.3.jar) 
	UCHIJAAAAAA	StorageDrawers{1.8.9-2.6.1} [Storage Drawers] (StorageDrawers-1.8.9-2.6.1.jar) 
	UCHIJAAAAAA	storagenetwork{1.8.1} [Storage Network] (StorageNetwork-1.8.9-1.8.1.jar) 
	UCHIJAAAAAA	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCHIJAAAAAA	witherchargingfix{1.0.0} [Wither Charging Fix] (witherchargingfix-1.8.9-1.0.0-0-universal.jar) 
	UCHIJAAAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  li.cil.oc.common.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* ActuallyAdditionsAPI (8) from ActuallyAdditions-1.8.9-r26.jar
		* Baubles|API (1.1.1.0) from Baubles-1.8.9-1.1.3.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.8.9-2.0.0-20.jar
		* BotaniaAPI (77) from Botania-unofficial.r1.8-299.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-8.6.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from EnderRift-0.10.0.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from quantumflux-1.8.9-2.0.1.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.8.9-1.1.4beta22.jar
		* EiraIRC|API (2.0) from eirairc-mc1.8.9-4.9.12.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.8.9-1.4.247.jar
		* GameAnalyticsAPI (1.2) from AuraCascade-592.jar
		* HydCraft|API (1.0) from HydCraft-1.8.9-3.1.65-universal.jar
		* IronBackpacks|API (0.4) from IronBackpacks-1.8.9-2.0.5.jar
		* jeresources|API (0.4.0) from JustEnoughResources-1.8.9-0.4.0.jar
		* journeymap|client-api (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-display (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-event (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-model (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-util (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.12.180.jar
		* McJtyLib (1.8.9-1.8.1beta10) from mcjtylib-1.8.9-1.8.1beta10.jar
		* moarcarts|API (1.0) from moarcarts-1.8.9-2.0.1-16.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* PneumaticCraftApi (1.0) from PneumaticCraft-1.8.9-1.13.8-12-universal.jar
		* pressureAPI (1.3.0.25) from pressure-1.3.0.25-mc1.8.9.jar
		* PsiAPI (1) from Psi-beta-23.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* Thaumcraft|API (5.2.3.0) from Thaumcraft-1.8.9-5.2.4.jar
		* WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
	Launched Version: forge-11.15.1.1808
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

**Comment by ftog-thorgal** [comment]
Can you replicate this crash or was it one-time only?

**Comment by ftog-thorgal** [comment]
Player has been online so I am guessing it isn't crashing anymore.
