### ISSUE TITLE
Crash Report by Natural_Body

### ISSUE THREAD

**Issue by Dosbound** [ftog-thorgal/Avant#11]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 30.03.16 17:28
Description: Tesselating block in world

java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:145)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.build(TRSRBakedModel.java:162)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:63)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:136)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:95)
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175022_a(ElecBlockRendererDispatcher.java:80)
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175018_a(ElecBlockRendererDispatcher.java:43)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
	at gcewing.sg.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:145)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.build(TRSRBakedModel.java:162)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:63)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:136)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:95)
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175022_a(ElecBlockRendererDispatcher.java:80)

-- Block being tesselated --
Details:
	Block type: ID #1498 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.block.BlockToolTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-110,63,313), Chunk: (at 2,3,9 in -7,19; contains blocks -112,0,304 to -97,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at elec332.core.client.model.replace.ElecBlockRendererDispatcher.func_175018_a(ElecBlockRendererDispatcher.java:43)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
	at gcewing.sg.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Natural_Body'/28403052, l='MpServer', x=-43,60, y=64,00, z=218,32]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 83,00,94,00,-18,00 - World: (83,94,-18), Chunk: (at 3,5,14 in 5,-2; contains blocks 80,0,-32 to 95,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 8983638 game time, 5427992 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityZombie['Zombie'/28405809, l='MpServer', x=-31,50, y=12,00, z=221,50], EntityCreeper['Creeper'/28405808, l='MpServer', x=-43,94, y=54,00, z=192,94], EntitySkeleton['Skeleton'/28405811, l='MpServer', x=-52,19, y=55,00, z=235,53], EntitySkeleton['Skeleton'/28405810, l='MpServer', x=-29,22, y=30,00, z=213,56], EntitySkeleton['Warped Skeleton'/28405813, l='MpServer', x=-56,50, y=24,00, z=192,50], EntitySkeleton['Skeleton'/28405941, l='MpServer', x=21,50, y=25,00, z=286,50], EntitySkeleton['Skeleton'/28405812, l='MpServer', x=-47,53, y=14,00, z=197,09], EntityAuraNode['Aura Node'/28405940, l='MpServer', x=-111,50, y=70,50, z=154,50], EntityCreeper['Creeper'/28405815, l='MpServer', x=-54,97, y=21,00, z=206,56], EntitySkeleton['Skeleton'/28405814, l='MpServer', x=-54,88, y=30,00, z=198,63], EntityZombie['Zombie'/28405817, l='MpServer', x=-18,66, y=31,00, z=226,91], EntityZombie['Zombie'/28405816, l='MpServer', x=-23,53, y=45,00, z=212,13], EntitySpider['Spider'/28405819, l='MpServer', x=-32,28, y=30,00, z=179,72], EntitySquid['Squid'/28405818, l='MpServer', x=-62,50, y=53,80, z=220,26], EntityPlayerSP['Natural_Body'/28403052, l='MpServer', x=-43,60, y=64,00, z=218,32], EntitySkeleton['Skeleton'/28405821, l='MpServer', x=-78,50, y=30,00, z=196,50], EntityAuraNode['Aura Node'/28405949, l='MpServer', x=-90,50, y=70,50, z=234,50], EntityPech['Pech Mage'/28405820, l='MpServer', x=-39,50, y=13,00, z=248,50], EntityPech['Pech Forager'/28405823, l='MpServer', x=-10,78, y=23,00, z=201,53], EntityZombie['Zombie'/28405951, l='MpServer', x=-15,09, y=50,00, z=139,50], EntitySquid['Squid'/28405822, l='MpServer', x=-74,72, y=58,97, z=211,03], EntityZombie['Zombie'/28405950, l='MpServer', x=-5,50, y=41,00, z=139,50], EntityAuraNode['Aura Node'/28405924, l='MpServer', x=19,50, y=57,50, z=149,50], EntityCreeper['Creeper'/28405927, l='MpServer', x=8,56, y=48,00, z=143,94], EntityZombie['Zombie'/28405933, l='MpServer', x=-102,16, y=22,00, z=204,63], EntitySkeleton['Skeleton'/28405805, l='MpServer', x=-47,50, y=56,00, z=216,50], EntityCreeper['Creeper'/28405804, l='MpServer', x=-36,50, y=13,00, z=217,50], EntityCreeper['Creeper'/28405807, l='MpServer', x=-42,50, y=22,00, z=204,78], EntityRabbit['Rabbit'/28405935, l='MpServer', x=0,41, y=64,00, z=156,75], EntitySkeleton['Skeleton'/28405934, l='MpServer', x=17,69, y=53,16, z=154,47], EntityZombie['Zombie'/28405806, l='MpServer', x=-45,47, y=55,00, z=214,63], EntityItem['item.item.string'/28405953, l='MpServer', x=-81,38, y=10,00, z=266,78], EntitySpider['Spider'/28405952, l='MpServer', x=-80,72, y=11,09, z=256,66], EntityAuraNode['Aura Node'/28405957, l='MpServer', x=2,50, y=80,50, z=191,50], EntityAuraNode['Aura Node'/28405958, l='MpServer', x=-15,50, y=69,50, z=169,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1650727576 bytes (1574 MB) / 3366453248 bytes (3210 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1808 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJA	Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJA	OpenComputers|Core{1.6.0.2-beta.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJA	ActuallyAdditions{1.8.9-r26} [Actually Additions] (ActuallyAdditions-1.8.9-r26.jar) 
	UCHIJA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJA	ArmorHud{1.0.0} [ArmorHud] (ArmorHud-1.8.9-1.0.0.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.4.1} [Aroma1997Core|Helper] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.8.9-1.1.2.0.jar) 
	UCHIJA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJA	aura{592} [Aura Cascade] (AuraCascade-592.jar) 
	UCHIJA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJA	Automagy{2.0.1} [Automagy] (Automagy-1.8.9-2.0.1.jar) 
	UCHIJA	basemetals{1.7.4} [Base Metals] (BaseMetals-1.7.4.jar) 
	UCHIJA	bdlib{1.10.0.31} [BD Lib] (bdlib-1.10.0.31-mc1.8.9.jar) 
	UCHIJA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1935-universal.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJA	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCHIJA	JEI{2.28.12.180} [Just Enough Items] (jei_1.8.9-2.28.12.180.jar) 
	UCHIJA	BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-20.jar) 
	UCHIJA	bookshelfapi{2.3.7} [Bookshelf] (Bookshelf-API-1.8.9-2.3.7.jar) 
	UCHIJA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJA	Chameleon{1.8.9-1.1.1} [Chameleon] (Chameleon-1.8.9-1.1.1.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJA	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCHIJA	chiselsandbits{8.6} [Chisels & Bits] (chiselsandbits-8.6.jar) 
	UCHIJA	ChiselsBytes{0.2} [Chisels & Bytes] (ChiselsBytes-1.8.9-0.2.jar) 
	UCHIJA	clayworldgen{v1.0.0} [Clay WorldGen] (ClayWorldGen-1.0.1.jar) 
	UCHIJA	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-1.8.8-3.0.2.jar) 
	UCHIJA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCHIJA	ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
	UCHIJA	deepresonance{1.1.4beta22} [DeepResonance] (deepresonance-1.8.9-1.1.4beta22.jar) 
	UCHIJA	eirairc{4.9.12} [EiraIRC] (eirairc-mc1.8.9-4.9.12.jar) 
	UCHIJA	poweradvantage{1.5.4} [Power Advantage] (PowerAdvantage-1.5.4.jar) 
	UCHIJA	electricadvantage{1.1.2} [Electric Advantage] (ElectricAdvantage-1.1.2.jar) 
	UCHIJA	enderrift{0.10.0} [Ender-Rift] (EnderRift-0.10.0.jar) 
	UCHIJA	enderutilities{0.5.0} [Ender Utilities] (enderutilities-1.8.9-0.5.0.jar) 
	UCHIJA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UCHIJA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJA	pressure{1.3.0.25} [Pressure Pipes] (pressure-1.3.0.25-mc1.8.9.jar) 
	UCHIJA	advgenerators{0.9.19.9} [Advanced Generators] (generators-0.9.19.9-mc1.8.9.jar) 
	UCHIJA	gravestone{1.1.3} [Gravestone] (Gravestone Mod 1.1.3.jar) 
	UCHIJA	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UCHIJA	HydCraft{1.8.9-3.1.65} [Hydraulicraft] (HydCraft-1.8.9-3.1.65-universal.jar) 
	UCHIJA	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCHIJA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJA	ironbackpacks{1.8.9-2.0.5} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.5.jar) 
	UCHIJA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCHIJA	llor{1.0.7-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.8.9.jar) 
	UCHIJA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJA	moarcarts{2.0.1-16} [MoarCarts] (moarcarts-1.8.9-2.0.1-16.jar) 
	UCHIJA	modtweaker2{1.0.0} [Mod Tweaker 2] (ModTweaker2-1.0.0.jar) 
	UCHIJA	numina{0.5.0-001} [Numina] (Numina-0.5.0-001.jar) 
	UCHIJA	powersuits{0.11.0-003} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.8.9-0.11.0-003.jar) 
	UCHIJA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJA	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.8.9.jar) 
	UCHIJA	cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurntiureModv3.6.1(1.8.9).jar) 
	UCHIJA	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UCHIJA	neotech{2.4.4} [NeoTech] (NeoTech-1.8.9-2.4.4.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6.jar) 
	UCHIJA	notenoughwands{1.3.0} [Not Enough Wands] (notenoughwands-1.8.9-1.3.0.jar) 
	UCHIJA	OpenComputers{1.6.0.2-beta.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar) 
	UCHIJA	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
	UCHIJA	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UCHIJA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJA	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UCHIJA	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCHIJA	xreliquary{1.3.1.222} [Reliquary] (Reliquary-1.3.1.222.jar) 
	UCHIJA	reptilemod{3.1.0} [Reptile Mod] (reptilemod-1.8.9-3.2.1-40.jar) 
	UCHIJA	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJA	rftools{4.23beta35} [RFTools] (rftools-1.8.9-4.23beta35.jar) 
	UCHIJA	rftoolsdim{4.22beta30} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta30.jar) 
	UCHIJA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJA	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.8.8.jar) 
	UCHIJA	routerreborn{1.8.9-3.0.5.14b_universal} [Router Reborn] (RouterReborn-1.8.9-3.0.5.14b_universal.jar) 
	UCHIJA	SGCraft{1.11.0} [Greg's SG Craft] (SGCraft-1.11.0-mc1.8.9.jar) 
	UCHIJA	steamadvantage{1.5.3} [Steam Advantage] (SteamAdvantage-1.5.3.jar) 
	UCHIJA	StorageDrawers{1.8.9-2.6.1} [Storage Drawers] (StorageDrawers-1.8.9-2.6.1.jar) 
	UCHIJA	storagenetwork{1.8.1} [Storage Network] (StorageNetwork-1.8.9-1.8.1.jar) 
	UCHIJA	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCHIJA	witherchargingfix{1.0.0} [Wither Charging Fix] (witherchargingfix-1.8.9-1.0.0-0-universal.jar) 
	UCHIJA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  li.cil.oc.common.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* ActuallyAdditionsAPI (8) from ActuallyAdditions-1.8.9-r26.jar
		* Baubles|API (1.1.1.0) from Baubles-1.8.9-1.1.3.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.8.9-2.0.0-20.jar
		* BotaniaAPI (77) from Botania-unofficial.r1.8-299.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-8.6.jar
		* CoFHAPI (1.8.9R1.2.0B1) from EnderRift-0.10.0.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Bookshelf-API-1.8.9-2.3.7.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.8.9-1.1.4beta22.jar
		* EiraIRC|API (2.0) from eirairc-mc1.8.9-4.9.12.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.8.9-1.4.247.jar
		* GameAnalyticsAPI (1.2) from AuraCascade-592.jar
		* HydCraft|API (1.0) from HydCraft-1.8.9-3.1.65-universal.jar
		* IronBackpacks|API (0.4) from IronBackpacks-1.8.9-2.0.5.jar
		* jeresources|API (0.4.0) from JustEnoughResources-1.8.9-0.4.0.jar
		* journeymap|client-api (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-display (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-event (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-model (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-util (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.12.180.jar
		* McJtyLib (1.8.9-1.8.1beta10) from mcjtylib-1.8.9-1.8.1beta10.jar
		* moarcarts|API (1.0) from moarcarts-1.8.9-2.0.1-16.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* PneumaticCraftApi (1.0) from PneumaticCraft-1.8.9-1.13.8-12-universal.jar
		* pressureAPI (1.3.0.25) from pressure-1.3.0.25-mc1.8.9.jar
		* PsiAPI (1) from Psi-beta-23.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.1.jar
		* Thaumcraft|API (5.2.3.0) from Thaumcraft-1.8.9-5.2.4.jar
		* WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
	Launched Version: forge-11.15.1.1808
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz

**Comment by ftog-thorgal** [comment]
Can you replicate this crash or was it one-time only?

**Comment by Dosbound** [comment]
Everytime i Login into the Server. After 1 - 4 Sek. The Game crashed. Maybe i have some items in my inventory that causes the Problem ?

**Comment by Dosbound** [comment]
Also i changed the Java version from 1.8.0_25 to 77

**Comment by ftog-thorgal** [comment]
Do you remember what the last item was you crafted before you crashed? There are two lines, one about Tinkers Construct and one about ArchitectureCraft and we aren't sure what causes it yet.

**Comment by Dosbound** [comment]
I didn't Craft any ArchitectureCraft Item yet, i Think. The last Item i craft was an Tool Combined with all the generell tools like Shovel, Axe in One Item and two armor Pieces made of something is called black or coalquartz

**Comment by Dosbound** [comment]
Is it possible to Take all my items that are in my Inventory and put it Into a chest? Within Next Login ?

**Comment by ftog-thorgal** [comment]
I am going to remove the Tinkers tool you crafted last and let you know so you can log in again. Give me a minute.

**Comment by Dosbound** [comment]
take your time

**Comment by ftog-thorgal** [comment]
It was the Tinkers Crafting Station next to the bed. You know how the items are getting rendered on top of the stations now, we think that you had something in it that caused a render crash.
You should be fine to log in now.

**Comment by Dosbound** [comment]
Thank you for your fast help ! I found some dark oak wood planks in the crafting table

**Comment by Dosbound** [comment]
also someone set me on fire with a wand !
