### ISSUE TITLE
Missing Recipes in Hydrauliccraft mod

### ISSUE THREAD

**Issue by Shaktu** [ftog-thorgal/Avant#13]
there ar some missing recipes tha are essencial for the mod missing like pipes ang generatos

**Comment by ftog-thorgal** [comment]
I checked every block and they all have recipes. Have you actually looked at the changes from 1.7.10 to 1.8.9 Hydrauliccraft because the mod might've changed a lot. This isn't really something I can fix if it's broken but you need to report that to the mods github.
