### ISSUE TITLE
Unable to Join Server

### ISSUE THREAD

**Issue by ShadowsVengeance** [ftog-thorgal/Avant#17]
For some reason whenever I try to login to the server it stays at "logging in" while console loops this.

http://pastebin.com/XvwfCpNZ

Not sure what to make of this, maybe it's something at my base that's not letting me on. Im also not sure if anything happens server-side that will show more information.

P.S. This is Beans128

**Comment by ftog-thorgal** [comment]
We didn't make any changes server side since you were on earlier today.

**Comment by ShadowsVengeance** [comment]
I haven't been able to get on since like 2 nights ago. Might try reinstalling the pack when nobody's on the internet.

**Comment by ShadowsVengeance** [comment]
No luck :(

**Comment by ShadowsVengeance** [comment]
Glitch wiped my player data and im all good now.
