### ISSUE TITLE
Multiple crashes 

### ISSUE THREAD

**Issue by Bamrak** [ftog-thorgal/Avant#21]
This possibly may have something to do with flying and drawer controller. This was happening with the RFtools teleporter at WildRascal's base and resolved itself when the portal was removed outside of the chunk with the controller, Now my base has began to show the same issue with the same chunk with storage drawers without flight. 
[crash-2016-04-08_20.45.15-client.txt](https://github.com/ftog-thorgal/Avant/files/211045/crash-2016-04-08_20.45.15-client.txt)
[crash-2016-04-08_20.49.47-client.txt](https://github.com/ftog-thorgal/Avant/files/211048/crash-2016-04-08_20.49.47-client.txt)
[crash-2016-04-08_20.55.33-client.txt](https://github.com/ftog-thorgal/Avant/files/211046/crash-2016-04-08_20.55.33-client.txt)
[crash-2016-04-08_21.08.19-client.txt](https://github.com/ftog-thorgal/Avant/files/211047/crash-2016-04-08_21.08.19-client.txt)

**Comment by ftog-thorgal** [comment]
As this seems to be resolved since updating to the latest version I am going to close this.
