### ISSUE TITLE
BaseMetal ingots having no texture

### ISSUE THREAD

**Issue by NoobFortress2** [ftog-thorgal/Avant#9]
this might not be that severe, but for prettyness's sake it's annoying

A solution would be to add the Ore Dictionary Converter mod
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286974-ore-dictionary-converter

**Comment by fattay** [comment]
i also have no base metal textures

**Comment by ftog-thorgal** [comment]
We need to wait for the mod to be updated, it's been reported to them.
